### ISSUE TITLE
Email field

### ISSUE THREAD

**Issue by ewydler** [SwimOrDieSoftware/Wordpress-RSVP-Plugin#14]
Hi, great plugin. I am struggling to find out why my xls import shows brings in some emails and other not. The names and associations seem to be perfect.

**Comment by medelibero** [comment]
Hi,

  By chance are the ones that the emails are not importing are they associated guests and do the associations happen before the entries with their email information?  Would you be willing to share your spreadsheet with me?

Thanks,
Mike

**Comment by ewydler** [comment]
Hi Mike,

Thanks for the quick reply,
I can share the spreadsheet with you but I will edited the emails. Maybe
you can understand what is going on from there? The ones that are left with
a "-" was left as is. As they don't have an email and their partner would
RSVP for them. Hope it makes sense.

Thanks,
Ed


ᐧ


Edward Wydler | UX / Product Design | M:  0776 204 7916 |
ewydler@gmail.com | www.ewydler.com | Heart Atelier
<http://www.atelierheart.com>

**Comment by medelibero** [comment]
Sounds good. Feel free to email the spreadsheet to me instead of GitHub if it is easier. My email is mikede@mde-dev.com

**Comment by medelibero** [comment]
I just released 2.2.6 which fixes this issue.
