### ISSUE TITLE
Passcode

### ISSUE THREAD

**Issue by lowe493** [SwimOrDieSoftware/Wordpress-RSVP-Plugin#15]
Not really an issue more of a question,

How would i make the passcode field show as text apposed to a password, also how would i make it so the passcode field is a number field so an iphone would only show the Passcode keyboard?

![screen shot 2016-10-23 at 12 30 34](https://cloud.githubusercontent.com/assets/16779838/19625881/9c8749cc-991c-11e6-927f-4b16daf1a02e.png)

Thanks
Steve :)

**Comment by medelibero** [comment]
Hi,

  The easiest way to do this is with a little bit of JavaScript it would look like...

`jQuery("#rsvpPlugin #passcode").attr("type", "text")` 

Which would change the password input to text if you want it to just show number I would set the type to "number". 

Let me know how else I can help.

Thanks,
Mike

**Comment by lowe493** [comment]
Hi Mike, thanks for responding :), I'm guessing i would add this using the wordpress editor on one of the PHP files?

Thanks
Steve

**Comment by medelibero** [comment]
Hi Steve,

  Yea, you would add a new JavaScript file to your theme or modify an existing one. 

-Mike

**Comment by lowe493** [comment]
Hey Mike,
Just added that script into the template, everything worked just needed to alter the type to tel which brought up the numbers only keyboard :)

Thanks for you help
