### ISSUE TITLE
Feature request: Optional patrimonial (middle) names

### ISSUE THREAD

**Issue by jevgen** [SwimOrDieSoftware/Wordpress-RSVP-Plugin#16]
Many nations, including Britons, have tradition of Middle names, and patrimonial names used in official RSVPs and invitations mostly. I'd like to request a feature of optional adding of Middle name, which stands in between First and Last names if used.

**Comment by medelibero** [comment]
Hi,

  This feature is actually on my task list to add to the Pro version. 

-Mike
