### ISSUE TITLE
Newlines in CSV export

### ISSUE THREAD

**Issue by rolandme** [SwimOrDieSoftware/Wordpress-RSVP-Plugin#22]
When using the export function if associated attendees are present, at the end of each associated attendee a newline is inserted in the CSV-file, which causes it to be misaligned when imported in Excel.

Suggestion: in wp-rsvp.php on line 729, change the \r\n at the end to a semicolon (or a different separation character).
`$csv .= rsvp_handle_text_encoding( trim( stripslashes( $assc->firstName." ".$assc->lastName ) ) )."; ";`
The last associated attendee will be ended with a semicolon now as well, in my opinion it would be nice if the semicolon was only present between attendees.

Moreover, if people use newlines in their notes, this cause the CSV-file to be misaligned as well.

Suggestion: on line 741, add something which replaces newlines with a space.
`$csv .= "\"".(preg_replace("/[\n\r]/"," ", str_replace("\"", "\"\"", stripslashes($a->note)))."\"");`

**Comment by medelibero** [comment]
I just released 2.4.8 to change the newline to a comma for the associated first and last names. 

I am not able to recreate a problem with the notes when they enter a new line. What program are you using to open it to show the misalingment? I could see it if you opened it in a text editor but not when using Excel or Numbers. I am hesitant to strip newlines out of a note.
