### ISSUE TITLE
Can't use custom questions

### ISSUE THREAD

**Issue by crocoolivier** [SwimOrDieSoftware/Wordpress-RSVP-Plugin#24]
Hi,
I have a big problem with this plugin. I can't use custom questions.
If i click sur add question, i can't see the question type list. 
![image](https://user-images.githubusercontent.com/866852/52261922-2dc92400-292b-11e9-80a9-3dec7004e98d.png)

In the database 

![image](https://user-images.githubusercontent.com/866852/52261940-41748a80-292b-11e9-9fee-ecc3ffa07af0.png)

And i if i write a custom question and i click on save, there is no insert in the database.

I'm in last wordpress version 5.0.3
Thx in advance,

**Comment by crocoolivier** [comment]
Ok i found the solution.

**Comment by medelibero** [comment]
What is your database collation? Are you running on Windows or Linux? Often times I have just seen this problem go away when a person deactivates and reactivates the plugin.
