### ISSUE TITLE
Adding custom questions doesn't work

### ISSUE THREAD

**Issue by Pro** [SwimOrDieSoftware/Wordpress-RSVP-Plugin#30]
It seems that the form action URL for adding a custom question is wrong.

If I press the "Add custom question" Link, the corresponding form opens. Then after pressing "Save question" it redirects to a page which doesn't exist: `wp-admin/admin.php?page=rsvp-admin-custom-question`

If I manually change the form action URL to `wp-admin/admin.php?page=rsvp-admin-questions&action=add` the question is added.

I'm using version 2.7.0

**Comment by Pro** [comment]
I manually re-added the following lines, and now it's working as it should:

https://github.com/SwimOrDieSoftware/Wordpress-RSVP-Plugin/commit/67029435d0c82b657b09c0772ecd8393eeea5666#diff-d993fe7fe55b2d7b87d8b6cb8de5482aL1863

**Comment by medelibero** [comment]
Sorry about that. I will get it fixed later today and released.

**Comment by medelibero** [comment]
Once again, sorry about this. I just released 2.7.1 which fixes this problem.
